### ISSUE TITLE
Events won't show on event page

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#102]
I'm raising the white flag on this one I can't figure out why this customer's events won't show on the event page.

I need a fresh eyes to take a look.

Here's the site:  http://truthchurch.com/
Event page:  http://truthchurch.com/upcoming-events/
Sample event page:  http://truthchurch.com/event/labour-day-conference-2015/
The Events Calendar is activated
All the plugins have been deactivated one at a time to see if one was causing a conflict
I flushed out the permalinks

Admin:
Username: temp_admin
Password: 41%_Of.,/hbNhKA
http://truthchurch.com/wp-login.php

Customer thread:  https://secure.helpscout.net/conversation/67391927/3156/

**Comment by garand** [comment]
This will be something for Wednesday.

**Comment by garand** [comment]
We're going to need @chriswallace to look at this as well.

I confirmed that the events page has the correct template set, but I can't get any events to display on that page.

**Comment by angela-crist** [comment]
@chriswallace I have a few customers that this is happening for. They can't get their events to display on the events page and they are using the correct template.  Please advise.  See above.

**Comment by angela-crist** [comment]
@chriswallace Please take a look at this it will probably only take you 5 mins but I just need to know how to fix it because it comes up quite often.

**Comment by chriswallace** [comment]
OK, so two problems. They are not using the right "events" page. They should not create a page for events, just use the built-in events archive here: http://truthchurch.com/events/

Second, this particular site had set an option for The Events Calendar which changed the display template for the Events Archive page here:

http://lift.d.pr/1leAb (from the Events > Settings area for The Events Calendar).

Once those two things were "fixed" they are all set, but they will need to link to their events archive instead of the events page they created to add it to their menu properly.
